# netlify.toml
[build]
  publish = "build" # Remplacez par le répertoire de votre site
  command = "npm run build" # Remplacez par votre commande de build

[[redirects]]
  from = "/ancienne-url"
  to = "/nouvelle-url"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

# Configuration de l'URL du site
[context.production.environment]
  NETLIFY_SITE_URL = "https://tidiprint.netlify.app"